### ISSUE TITLE
MemoryError with np.save

### ISSUE THREAD

**Issue by yyunhh** [meghshukla/ActiveLearningForHumanPose#1]
Hello, thanks for your work.

May I ask how much RAM you use to execute the project?

Because I encounter the issue: 
```
Traceback (most recent call last):
File “main.py”, line 854, in <module>
main()
File “main.py”, line 810, in main
mpii_dict, max_persons_in_mpii = load_hp_dataset(mpii=True, conf=conf)
File “D:\Research\math-analysis-learningloss\code\dataloader.py”, line 387, in load_hp_dataset
return load_mpii(lambda_head=mpii_params[‘lambda_head’], del_extra_jnts=mpii_params[‘del_extra_jnts’],
File “D:\Research\math-analysis-learningloss\code\dataloader.py”, line 216, in load_mpii
np.save(file=os.path.join(root, ‘cached’, ‘mpii_cache_{}.npy’.format(string)),
File “<array_function internals>”, line 5, in save
File “C:\ProgramData\Anaconda3\envs\AL\lib\site-packages\numpy\lib\npyio.py”, line 528, in save
format.write_array(fid, arr, allow_pickle=allow_pickle,
File “C:\ProgramData\Anaconda3\envs\AL\lib\site-packages\numpy\lib\format.py”, line 664, in write_array
pickle.dump(array, fp, protocol=3, **pickle_kwargs)
MemoryError
```

I wonder the issue is about when I save the img_dict to .npy by using np.save 
The .npy file is too big and got memory error?

Because I only got 16G RAM of equipment, any suggestion?  :(
Or I reduce some mpii data to make the img_dict smaller to save?

Thanks.

**Comment by meghshukla** [comment]
Hi!
Our setup assumes access to a large amount of RAM > 16GB, since we load all MPII/LSPET images into memory.
Working with smaller amount of RAM ~16GB is certainly possible.
Instead of loading all images into memory, the code could be tweaked to load these images directly from the disk to RAM in dataloader.py: __getitem__().

Thanks for reaching out!
