### ISSUE TITLE
evaluation metric

### ISSUE THREAD

**Issue by cailile** [meghshukla/ActiveLearningForHumanPose#2]
Hi,

I notice that the PCKh_mpii.csv file output by the code stores a matrix, with PCK at different thresholds. May I know how to get the final single value for performance benchmarking? Thanks!

**Comment by meghshukla** [comment]
Hello,

Thank you for using our code.
You can take the mean for PCKh at 0.5 threshold.
PCKh@0.5 is the standard threshold(Stacked Hourglass, ECCV 2016)

Also a short reminder that this threshold differs on the dataset too.
For instance LSP uses PCK and not PCKh hence the threshold is 0.2 in that setup.

Best,
Megh

**Comment by cailile** [comment]
Thanks a lot for the reply. I notice that the thresholds are generated by:
threshold = np.linspace(0, 1, num=20)
which does not have the 0.5 value:
<img width="571" alt="image" src="https://github.com/meghshukla/ActiveLearningForHumanPose/assets/27752148/861b643c-c115-4129-b063-55e58bbc8235">
In this case, shall I use the closest 0.526316 or modify threshold = np.linspace(0, 1, num=20) to produce exactly 0.5?

**Comment by meghshukla** [comment]
I have used 0.526316 as the threshold which is consistent across all evaluation.
Please let me know if I need to clarify anthing else!

**Comment by cailile** [comment]
Thanks a lot! I am clear now.
